---
name: aio-toolbox build
on:
  push:
    branches:
      - "main"
    paths:
      - "src/aio/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/aio/**"
  workflow_dispatch:
jobs:
  aio-toolbox:
    uses: ixxeL-actions/workflows/.github/workflows/docker-build.yaml@main
    with:
      component: aio
      workingdir: src/aio
      img-name: toolbox
      podman-username: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      git-token: ${{ secrets.PAT }}
      DOCKER_IO_PWD: ${{ secrets.DOCKER_IO_PWD }}
